[site]
title = "Sirui LIU (Sirius)"
description = "PhD student at the Teachers College, Columbia University."
favicon = "/favicon.svg"
last_updated = "Feb 25, 2025"

[author]
name = "Sirui LIU (Sirius)"
title = "PhD Student"
institution = "Teachers College, Columbia University"
avatar = "/profile1.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "sl5576@tc.columbia.edu"
location = "New York, USA"
location_url = "https://maps.app.goo.gl/oBQ8XBV2TV5Rv6cKA"
location_details = [
  "Room 1055, Building 528,",
  "528 W 121st St, New York, NY 10027"
]
google_scholar = "https://scholar.google.com/citations?user=9idTRJ4AAAAJ&hl=en&oi=sra"
orcid = "https://orcid.org/0000-0001-8233-9494"
github = "ID: Sirius-Sirui"
linkedin = "www.linkedin.com/in/sirui-liu-277a08200"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
