[[news]]
date = "2026-1"
content = "Our MSUD project abstract has been accepted by the 2026 GMDI conference! 🎉"

[[news]]
date = "2024-09"
content = "Starting my PhD at Teachers College, Columbia University"
