type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "Doctoral Dialogues Committee Members"
subtitle = "Biobehavioural Sicence Department"
date = "2025"
content = "Helping prepare for the Doctoral Dialogues topics for each semester; Communicate and cooperate with other Committe members."
